# Cloudflare Worker 配置文件
name = "dol-lyra-signaling-worker"
main = "signaling-server.js"
dev = {
  command = "node --input-type=module signaling-server.js"
}

# 定义路由规则
[[routes]]
pattern = "https://dol-lyra-signaling-worker.your-account.workers.dev/*"
priority = 1

# 环境变量配置
[vars]
# 可以在这里定义环境变量
DEBUG = false