name: Build HTML Only

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/workflows/trigger.yaml"
      - ".github/workflows/deploy-hub.yaml"
  workflow_dispatch:

env:
  DOWNLOAD_RELEASE_TEMP_PATH: ${{ github.workspace }}/html-output
  MODLOADER_HTML_NORMAL_FILENAME: "index.html"
  MANIFEST_JSON_NORMAL_FILENAME: "manifest.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Temp Directory
        run: |
          mkdir -p "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}"

      - id: getRelease
        name: Download HTML Template
        uses: robinraju/release-downloader@v1.12
        with:
          repository: "DoL-Lyra/DoLModLoaderBuild"
          latest: true
          fileName: "DoL-ModLoader-*.zip"

      - name: Extract HTML Files
        run: |
          unzip -q ${{ fromJson(steps.getRelease.outputs.downloaded_files)[0] }} -d ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}
          mv "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/Degrees of Lewdity.html" "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/${{ env.MODLOADER_HTML_NORMAL_FILENAME }}"
          cp -r .github/pwa/* ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}

      - name: Modify HTML for Cloudflare Pages
        shell: python3 {0}
        run: |
          import os
          import json

          # 获取环境变量
          MODLOADER_HTML_NORMAL_FILENAME = os.environ.get("MODLOADER_HTML_NORMAL_FILENAME")
          DOWNLOAD_RELEASE_TEMP_PATH = os.environ.get("DOWNLOAD_RELEASE_TEMP_PATH")
          MANIFEST_JSON_NORMAL_FILENAME = os.environ.get("MANIFEST_JSON_NORMAL_FILENAME")

          # 修改 HTML 文件
          html_path = f"{DOWNLOAD_RELEASE_TEMP_PATH}/{MODLOADER_HTML_NORMAL_FILENAME}"
          with open(html_path, "r+", encoding="utf-8") as html_file:
              html_content = html_file.read()
              insert_index = html_content.find('<meta charset="UTF-8" />')
              html_content = html_content[:insert_index] + \
              f"<link rel=\"manifest\" href=\"{MANIFEST_JSON_NORMAL_FILENAME}\">\n" + html_content[insert_index:]
              html_file.seek(0)
              html_file.truncate()
              html_file.write(html_content)

              # 修改 manifest.json
              manifest_path = f"{DOWNLOAD_RELEASE_TEMP_PATH}/{MANIFEST_JSON_NORMAL_FILENAME}"
              with open(manifest_path, "r+", encoding="utf-8") as manifest_file:
              manifest_data = json.loads(manifest_file.read())
              manifest_data["scope"] = f"/${{ github.event.repository.name }}/"
              manifest_data["start_url"] = f"/${{ github.event.repository.name }}/"
              manifest_file.seek(0)
              manifest_file.truncate()
              manifest_file.write(json.dumps(manifest_data, indent=2))


      - name: Pack HTML Artifact
        run: |
          zip -qr ${{ github.workspace }}/html-artifact.zip ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/*

      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-artifact
          path: ${{ github.workspace }}/html-artifact.zip

  deploy-cf-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download HTML Artifact
        uses: actions/download-artifact@v4
        with:
          name: html-artifact

      - name: Extract HTML Files
        run: |
          unzip -q html-artifact.zip -d ./html-output

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          api-token: ${{ secrets.CF_PAGES_API_TOKEN }}
          project-name: "dol-lyra-html"
          directory: "./html-output"
          framework: "custom"
          build-command: ""
