name: Build HTML Only

on:
  push:
    branches:
      - main
    paths:
      - ".github/pwa/**"
      - "**/*.html"
      - "**/*.json"
      - "**/*.js"
  workflow_dispatch:

env:
  MODLOADER_HTML_NORMAL_FILENAME: "index.html"
  MANIFEST_JSON_NORMAL_FILENAME: "manifest.json"
  DOWNLOAD_RELEASE_TEMP_PATH: ${{ github.workspace }}/html-output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 克隆 DoL-Lyra/Lyra 仓库
      - name: Clone DoL-Lyra/Lyra
        uses: actions/checkout@v4
        with:
          repository: DoL-Lyra/Lyra
          ref: main  # 可根据需要替换为特定 tag 或分支
          path: lyra-code

      # 下载 HTML 模板 ZIP 文件
      - name: Download HTML Template
        uses: robinraju/release-downloader@v1.12
        with:
          repository: "DoL-Lyra/DoLModLoaderBuild"
          latest: true
          fileName: "DoL-ModLoader-*.zip"
          extract: false
          token: ${{ github.token }}

      # 解压并重命名文件
      - name: Extract and Prepare Files
        run: |
          unzip -q DoL-ModLoader-*-132.zip -d ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}
          mv "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/Degrees of Lewdity.html" "${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/${{ env.MODLOADER_HTML_NORMAL_FILENAME }}"
          cp -r .github/pwa/* ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}

      # 修改 HTML 和 manifest.json
      - name: Modify HTML and Manifest
        shell: python3 {0}
        run: |
          import os
          import json

          # 获取环境变量
          MODLOADER_HTML = os.environ.get("MODLOADER_HTML_NORMAL_FILENAME")
          MANIFEST_JSON = os.environ.get("MANIFEST_JSON_NORMAL_FILENAME")
          TEMP_PATH = os.environ.get("DOWNLOAD_RELEASE_TEMP_PATH")

          # 修改 HTML 文件
          html_path = f"{TEMP_PATH}/{MODLOADER_HTML}"
          with open(html_path, "r+", encoding="utf-8") as html_file:
              html_content = html_file.read()
              insert_index = html_content.find('<meta charset="UTF-8" />')
              html_content = html_content[:insert_index] + \
                  f"<link rel=\"manifest\" href=\"{MANIFEST_JSON}\">\n" + html_content[insert_index:]
              html_file.seek(0)
              html_file.truncate()
              html_file.write(html_content)

          # 修改 manifest.json
          manifest_path = f"{TEMP_PATH}/{MANIFEST_JSON}"
          with open(manifest_path, "r+", encoding="utf-8") as manifest_file:
              manifest_data = json.load(manifest_file)
              manifest_data["scope"] = "/${{ github.event.repository.name }}/"
              manifest_data["start_url"] = "/${{ github.event.repository.name }}/"
              manifest_file.seek(0)
              manifest_file.truncate()
              manifest_file.write(json.dumps(manifest_data, indent=2))

      # 打包 HTML 资源
      - name: Pack HTML Artifact
        run: |
          zip -qr ${{ github.workspace }}/html-artifact.zip ${{ env.DOWNLOAD_RELEASE_TEMP_PATH }}/*

      # 上传 HTML 资源
      - name: Upload HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-artifact
          path: ${{ github.workspace }}/html-artifact.zip

  deploy-cf-pages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # 下载 HTML 资源
      - name: Download HTML Artifact
        uses: actions/download-artifact@v4
        with:
          name: html-artifact

      # 部署到 Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          api-token: ${{ secrets.CF_PAGES_API_TOKEN }}
          project-name: "dol-lyra-html"
          directory: "./html-output"
          framework: "custom"
          build-command: ""
